# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HizZNPtLVAvMT87I/ADstiP5Lh6FLXebFfl5jW7xbyt6/8gStZt5YQXMgwyLCWtB/lHY4/rWQds0VmzlE5F95fNbfCNxdbAdG3cjiBPIRNaS4WR1MFT0SNCoZCyoth3dXeomKIjqBWYAW6hsbEQORybC9s+swUyN5plnYswpjrRSwJuNEAiD+gDpzn2rXrGAEGEkssTid/CBePQwb6vSHBUjwzMiwV7ILiLVXFBBJ7rP1Xrww2l/mP9Svwdwty0rxSyeBrsivanG4edkLXp+QkVhohi1qP219Vvk3MEYmcYZZLndryMvkNE8noWbStnH8ZPp7rnvpV+MFaV6sRtrcLl8Tov+SnuZwfWhW8h7GRZSQxRHmhC0PqTUHiaQZEDzYxnBTO1jiTmD/wXuAID0pbyZScXSQvmKw3vr2qMzw8lHeVnfk4ZbTDrW1ci5ygqEtq/nveaZjDTNe+/lH54Y1wHC/Zg5D5evZETKdw3tDzRch9f/JMHodAxrPSEVpMSlGYkMi8nbJrB1d0iPUPqF4jtX0eJePeRhIbV7amsP9wYLrtEzOSqpIEIBfYK8E2+iM8/vTs1/4X8YeYAJm2b8jfwDuRJaRsjIvtEXhg5GyNd0drY6a4nySYc6b5TVXk+f3SnAXvM8SAfRCxyN8K3daMmrIqqvJD8ic3Czy25aRVg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml