travis:
  secure:
    BINSTAR_TOKEN: ZYt2hqsFr6Vh/zFMSVbHn+5f5niCipNCNaYFzqjtlCNLB7XX3YfllwtdWTEVeg/cBKq+luDcn+bMZBqvyp0+SSQSX8bjAD7QQBGFearwiFSEp4meajFd78coS15M7X0o1ynYJkUskCcg2LoHXfsUBx+eNNAvKX49uc+yfjDSADO22ePf/IRY2FETCKxJFEJIn0DLM5gnZev7vcCUVzmRR8hIEd3njLtOVUbnMAw1jXzU9PwJ6sGjy/leIS0cCvb28SzixXf29f3X5vchlIlOTGx47guId0ugju1w6doluc6eqT5XJARj09FsBdKaKHYRHNB+TPVsd4rUSqDusL07Q933fE/UXz37ieqeGJYA2g/0Ukcp5TxtLykCUTSOz5t2MJ1ZIlp5qJKSVn8YJL6y5yGGMNsnKLeQyaXg5oiCqrVL/NfkfkLMlrFudPH1QuE8uSYR1MoOdycad9fjNC9dAvfsqVqLzpiRWp8fjXl76pq8yt91P+8OR2TYcMMey/j5ckt8DGAWHrjs0sXBz82dRDzpT6EqMTAe1Mr80Ifrm/nSx4x0WFwtBRWLCCI7/Oh3ggnAu0cRpJ7zDYia+aGytqkPyl8/cFPtPoHjl4nUS3OJVkgUPdXIeLDioeoCy+eL7qDZTfNScg9Glj/b3JNU9p0wAishrmBeRjxf9m6Jr5I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
